# Navigation links

main:
  - name: Bio
    url: /
    weight: 10
  - name: Research
    url: /#research
    weight: 20
  - name: Publications
    url: /#publications
    weight: 30
  - name: Experience
    url: experience/
    weight: 40
  - name: Misc
    url: /#misc
    weight: 45
  - name: Gallery
    url: /#gallery
    weight: 46
  - name: Contact
    url: /#contact
    weight: 50
  - name: CV
    url: uploads/MAQian_Resume.pdf
    weight: 60
